name: Update CONTRIBUTORS file

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update CONTRIBUTORS.md
        uses: minicli/action-contributors@v3.3
        env:
          CONTRIB_REPOSITORY: ${{ github.repository }}
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
          CONTRIB_STENCIL_DIR: ${{ github.workspace }}/.stencil
          CONTRIB_TEMPLATE: contributors
      
      - name: Compute date
        id: date
        run: |
          echo "time=$(date +"%Y-%m-%d-%H%M%S")" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: automation/docs/contributors/${{ steps.date.outputs.time}}
          delete-branch: true
          title: "docs: update contributors list"
          commit-message: "docs: update contributors list"
          body: |
            Automated update of CONTRIBUTORS.md using minicli/action-contributors.
          labels: automated
