# Add automated checks on PRs
name: push-code-validate
on:
  push:
    paths-ignore:
        - "**/*.md"
        - ".github/ISSUE_TEMPLATE/**"
        - ".github/CODEOWNERS"
        - ".stencil/**"
        - "backendfiles/**"
        - "examples/**"
        - "docs/**"
        - ".gitignore"
        - "LICENSE"


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt check
        run: terraform fmt -check -recursive
      
      - name: Terraform validate
        run: |
          terraform init -backend=false
          terraform validate